### ISSUE TITLE
error - missiong /dev/vchiq

### ISSUE THREAD

**Issue by towster** [SimonKagstrom/tesla_dashcam_manager#4]
Dont think i did anything wrong but perhaps something not installed on the RPi. I get this error. Any suggestions?

docker compose up -d
WARN[0000] /root/docks/dashcam/docker-compose.yml: `version` is obsolete 
[+] Running 0/2
 ⠸ Network dashcam_default                    Created                                                                                                6.4s 
 ⠸ Container dashcam-tesla-dashcam-manager-1  Starting                                                                                               6.3s 
Error response from daemon: error gathering device information while adding custom device "/dev/vchiq": no such file or directory

**Comment by SimonKagstrom** [comment]
I don't remember doing anything special in my Rpi4 installation. In my `/boot/config.txt` I have this though:

```
# Enable DRM VC4 V3D driver
dtoverlay=vc4-kms-v3d
max_framebuffers=2
```

which maybe is related to that?

**Comment by towster** [comment]
Seems to already be there.. 

```
root # cat /boot/config.txt
DO NOT EDIT THIS FILE

The file you are looking for has moved to /boot/firmware/config.txt
```
```
root # cat /boot/firmware/config.txt
# For more options and information see
# http://rptl.io/configtxt
# Some settings may impact device functionality. See link above for details

# Uncomment some or all of these to enable the optional hardware interfaces
#dtparam=i2c_arm=on
#dtparam=i2s=on
#dtparam=spi=on

# Enable audio (loads snd_bcm2835)
dtparam=audio=on

# Additional overlays and parameters are documented
# /boot/firmware/overlays/README

# Automatically load overlays for detected cameras
camera_auto_detect=1

# Automatically load overlays for detected DSI displays
display_auto_detect=1

# Automatically load initramfs files, if found
auto_initramfs=1

# Enable DRM VC4 V3D driver
dtoverlay=vc4-kms-v3d
max_framebuffers=2

# Don't have the firmware create an initial video= setting in cmdline.txt.
# Use the kernel's default instead.
disable_fw_kms_setup=1

# Run in 64-bit mode
arm_64bit=1

# Disable compensation for displays with overscan
disable_overscan=1

# Run as fast as firmware / board allows
arm_boost=1

[cm4]
# Enable host mode on the 2711 built-in XHCI USB controller.
# This line should be removed if the legacy DWC2 controller is required
# (e.g. for USB device mode) or if USB support is not required.
otg_mode=1

[all]

usb_max_current_enable=1
gpu_mem_512=256
gpu_mem_1024=512
```

**Comment by towster** [comment]
So did some more searching on this.. I am using Raspberry Pi 5 with bookworm Raspbian.. 
vchiq is part of videocore - the /dev/vchiq is an interface to control it
videocore is installed - i can see modules loaded via lsmod
there is a module named bcm2835_mmal_vchiq - it is not loaded but i can load it via modprobe yet it does not create /dev/vchiq

**Comment by SimonKagstrom** [comment]
Ah, OK. I'm on a Rpi4.

Stupid question perhaps, but is the docker container for the tesla dashcam manager running?

**Comment by towster** [comment]
It would not run until I commented out this section:
```
    devices:
        - "/dev/vchiq:/dev/vchiq"
```

It doesnt seem to be doing anything yet it is running. Is there a logfile I can look at within the docker? I tried exec a sh into the docker and was looking around but couldnt find one. Or is there a manual way I can test it?

**Comment by towster** [comment]
I have teslausb setup to copy data to /media/usbdrive/teslausb
So like there i have a "SavedClips" and "SentryClips" directory..

After starting the dashcam manager docker it created the "work" and "processing" directory..
I have not enabled pigallery2 yet but i did configure it (i think correctly)..

My compose looks like this:

```
# Example snippet for docker-compose.yml.
version: "3"

services:

## Example setup for pigallery2, pigallery2 can be accessed at port 5000 here
#  pigallery2:
#    image: bpatrik/pigallery2:1.9.0-alpine
#    container_name: pigallery2
#    privileged: true
#    environment:
#      - NODE_ENV=production
#    volumes:
#      - "/var/lib/pigallery2/config:/app/data/config"
#      - "pigallery-db-data:/app/data/db"
#      - "/media/usbdrive/TeslaCam/photos:/app/data/images"
#      - "/tmp:/app/data/tmp"
#    ports:
#      - 5000:5000
#    restart: always

  tesla-dashcam-manager:
    image: simonkagstrom/tesla_dashcam_manager:latest
    restart: always
    environment:
        - TZ=America/Chicago
        - TESLA_DASHCAM_ARGUMENTS=--title_screen_map --text_overlay_fmt "{event_timestamp} {event_city}"
        - RETAIN_DAYS=365
        - DESTINATION_RETAIN_DAYS=0
#    devices:
#        - "/dev/vchiq:/dev/vchiq"
    volumes:
        - "/media/usbdrive/teslausb:/app/staging"
        - "/media/usbdrive/raw-storage:/app/raw-storage"
        - "/media/usbdrive/TeslaCam:/app/destination-path"

```
